### ISSUE TITLE
Create a website logo

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/projectshub#1]
Create a beautiful website logo

**Comment by imanirak** [comment]
open to taking this on! Any specific colors in mind?

**Comment by Ayushpanditmoto** [comment]
@imanirak  no specific requirements just create which looks good and simple

**Comment by Ayushpanditmoto** [comment]
@imanirak  working on this issue ??

**Comment by imanirak** [comment]
Yes! Coming up with some design ideas 😊 should be done by Wednesday

**Comment by imanirak** [comment]
can we close this issue & the auth?

**Comment by Ayushpanditmoto** [comment]
Yeah @imanirak sure you have done a great work
