### ISSUE TITLE
create a about us page 

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/projectshub#10]

**Comment by btrezzy** [comment]
Happy to create one, this is my first time contributing. Can you guide me for which site I should prepare a about us page for?

**Comment by imanirak** [comment]
@btrezzy  Seems like most of these issues are for the main project page itself [projectshub.org](https://www.projectshub.org/)  Once you fork and clone, run ```npm i ``` followed by ```npm run dev```
to get the environment running. The project is currently created with Next.js.

**Comment by Bashamega** [comment]
can I work on it?
just den what the content you want to be inside the about and I will create it

**Comment by Bashamega** [comment]
Please assign me

**Comment by Bashamega** [comment]
> Please assign me

@Ayushpanditmoto

**Comment by Cshiva773** [comment]
Can i work on this issue?

**Comment by Ayushpanditmoto** [comment]
@Cshiva773 sure

**Comment by Cshiva773** [comment]
The "About" page was previously added at the bottom of the website.


![Screenshot (13)](https://github.com/Ayushpanditmoto/projectshub/assets/104835495/dca040c5-edb0-447a-a52d-7d599bac4b4b)


![Screenshot (14)](https://github.com/Ayushpanditmoto/projectshub/assets/104835495/d2ffe434-db74-4253-96d2-27eb05e1110f)



should I create a new about us page?
