### ISSUE TITLE
Flutter app which alert for coding contest 

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/projectshub#13]

**Comment by ameyjoshi3068** [comment]
Hi Ayush, I can create the app. But making a complete app is not a small task. I would highly appreciate if you let me create multiple issues in this repo regarding app. Please add hacktoberfest label afterwards.
 So can you please assign me the issue?

**Comment by Ayushpanditmoto** [comment]
@ameyjoshi3068  yep you can also create issues wait i am aps9 creating some issues

**Comment by zykuriku** [comment]
i would like to work on this issue. Could you please tell more specifics that you want in the app and also please assign the issue to me?

**Comment by Ayushpanditmoto** [comment]
@zykuriku  i am thinking to create a app which show upcoming coding contest and companies OA Question like this type of app
