### ISSUE TITLE
create a home page demo ui static which contain card for blogs creative ideas are welcome

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/projectshub#14]

**Comment by ratishjain12** [comment]
Hey @Ayushpanditmoto I can work on this issue can provide me with the details of what exactly you want?

**Comment by Ayushpanditmoto** [comment]
@ratishjain12 just create a good ui static inspire from other website also acceptable

**Comment by ratishjain12** [comment]
Okay please assign to me I can work on this :)
