### ISSUE TITLE
Design event page 

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/projectshub#17]
which show upcoming hacathons and many more .. thinking to create job sections also

**Comment by imanirak** [comment]
Did you want separate routes for hackathons and jobs? or all on the same /events page?

**Comment by Ayushpanditmoto** [comment]
@imanirak  Well 
for events 
we can add hacathons and seminars in same route

for job and intern need different route , u name it as you want

extra route for all companies online assesment question (OA) like amazon asked this dsa questions , google asked this leetcode question that all i think now

**Comment by imanirak** [comment]
okay, I'll take this on for events. If you want to make another issue for jobs route, I'll get to it after if no one else picks it up.

**Comment by imanirak** [comment]
Sorry for delay, was busy with work. I want to finish this but I need a good API to grab these events, or we manually input them.

**Comment by Ayushpanditmoto** [comment]
@imanirak  currently just create a UI part and use local array of map data in future we will replace with manual api
