### ISSUE TITLE
Redesign Footer

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/projectshub#2]
Sent UI/UX

**Comment by sergomen** [comment]
Hello, Ayushpanditmoto! Can I try to solve this task?
If I can, do I need to create a figma file at first?

**Comment by Ayushpanditmoto** [comment]
Sure, @sergomen, please provide some sample designs, and we can proceed with our discussion afterward

**Comment by Bashamega** [comment]
Hello:)
Can I work on it?
this is the design
![image](https://github.com/Ayushpanditmoto/projectshub/assets/110662505/dad03490-82da-487c-9dd4-3e8d48b9eabe)

**Comment by imanirak** [comment]
I think it looks good! Did you want to take on more design cards so everything can be cohesive ? 👍🏼  @Bashamega

**Comment by Bashamega** [comment]
> I think it looks good! Did you want to take on more design cards so everything can be cohesive ? 👍🏼 @Bashamega

Thanks!
I am not planning on doing the cards, may be this week, let me just make a PR for it

**Comment by Ayushpanditmoto** [comment]
Hey @Bashamega, please include only high-quality icons for now. The current structure of the footer components seems good.

**Comment by Bashamega** [comment]
> Hey @Bashamega, please include only high-quality icons for now. The current structure of the footer components seems good.

I have made the pr please accept it

**Comment by Bashamega** [comment]
I will update the icons now, and replace them with some react icons

**Comment by Ayushpanditmoto** [comment]
@Bashamega listen bro my website footer look fine as of now.  only just replace these icons with react-icons as of now

**Comment by Bashamega** [comment]
> @Bashamega listen bro my website footer look fine as of now. only just replace these icons with react-icons as of now

done

**Comment by sergomen** [comment]
Oh, I thought I have to redesign the footer. Do I need to continue or have to choose another task? I can, it's not problem for me.

**Comment by Ayushpanditmoto** [comment]
@sergomen, please go ahead and share your design first before making any changes to the codebase.

**Comment by sergomen** [comment]
> @sergomen, please go ahead and share your design first before making any changes to the codebase.

Sure. I just trying to understand your project better to create some prototypes at first.

**Comment by pankajdharmik4** [comment]
Is the issue solved now?

**Comment by Ayushpanditmoto** [comment]
@pankajdharmik4 nope wana try ??

**Comment by pankajdharmik4** [comment]
Sure

**Comment by vishesh-hue** [comment]
can i take on the issue i can create a minimalistic footer for it

**Comment by vishesh-hue** [comment]
replytyyyymee
