### ISSUE TITLE
Design The Card Components

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/projectshub#25]
![Screenshot_2](https://github.com/Ayushpanditmoto/projectshub/assets/31253617/a9bc79a5-376c-43ee-84d9-c76610f55de6)

**Comment by kumar2023jha2000** [comment]
Can I work on this

**Comment by Ayushpanditmoto** [comment]
@kumar2023jha2000  Sure I am Assigning this task

**Comment by kumar2023jha2000** [comment]
Hi actually I having a trouble in understand that do j only need to make components or I have to design it and in img I have to make whole clone or just a card
This is my first contribution so can you tell me plz😅

**Comment by shoaib-31** [comment]
Hi, @kumar2023jha2000 if you are not making this component assign is to me please I have made many components like these...
