### ISSUE TITLE
Create a Custom 404 Error Page

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/projectshub#28]

**Comment by OleanjiKingCode** [comment]
@Ayushpanditmoto can i work on the 404 error page

**Comment by Ayushpanditmoto** [comment]
Sure @OleanjiKingCode

**Comment by Ayushpanditmoto** [comment]
@OleanjiKingCode any update ??

**Comment by OleanjiKingCode** [comment]
I dont have access to push to a new branch or should i fork it?

**Comment by Ayushpanditmoto** [comment]
Fork again @OleanjiKingCode and add that file not-found.tsx in root directory

**Comment by kiranrega** [comment]
The MR merged already for this issue. but may i know why its still in open ?
