### ISSUE TITLE
CONTRIBUTING.md is empty

### ISSUE THREAD

**Issue by ayushichoudhary-19** [Ayushpanditmoto/projectshub#41]
This file is empty. 
Even under the title, 'list of contributor', no name is mentioned.

**Comment by Ayushpanditmoto** [comment]
@ayushichoudhary-19  Create a CONTRIBUTING.md file where user can write their contribution name with their github id

**Comment by ayushichoudhary-19** [comment]
Okay

**Comment by ayushichoudhary-19** [comment]
Done: https://github.com/Ayushpanditmoto/projectshub/pull/45
