### ISSUE TITLE
Create a Custom api for codeforces and codechef

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/projectshub#47]
![Screenshot_4](https://github.com/Ayushpanditmoto/projectshub/assets/31253617/b1af0d80-6390-4301-b987-04e0ab599ef2)
I given you the folder structure your task is to create a api/codechef api/codeforce which will return upcoming contest in json format

**Comment by vidhan63-soe** [comment]
Hello @Ayushpanditmoto  ,
I am interested in resolving this issue, but I am getting  few problem during <code> setup and I don't why I cannot join your discord community.

**Comment by Ayushpanditmoto** [comment]
@vidhan63-soe  we don't have discord community 😅 just clone the repo and npm install after that npm run dev

**Comment by usrj03l** [comment]
i have added a codeforces api can you check the pr
the codechef api is difficult because there is no code api to get information and they made scraping hard

**Comment by Ayushpanditmoto** [comment]
@usrj03l  you need to scrap data from official website

**Comment by biswassushmita947** [comment]
I wanna work on this issues ?? is it still open ?? Ayush

**Comment by Ayushpanditmoto** [comment]
Omkay I am assigning this task to you happy coding

**Comment by biswassushmita947** [comment]
Thank you @Ayushpanditmoto

**Comment by Ayushpanditmoto** [comment]
@biswassushmita947  but make sure you we need to scrap upto date contest

**Comment by biswassushmita947** [comment]
@Ayushpanditmoto  Okay

**Comment by Codensity30** [comment]
is the issue resolved?

**Comment by Ayushpanditmoto** [comment]
@Codensity30 no

**Comment by Ayushpanditmoto** [comment]
@Codensity30 wanna work on this ?

**Comment by Codensity30** [comment]
yes, can work but first, let me understand the issue, what actually we want?

**Comment by Ayushpanditmoto** [comment]
We have to scrap the latest contest from official website make sure it will on server side we want fresh data

**Comment by Ayushpanditmoto** [comment]
I am thinking that i am already using 3rd party api to scrap but whenever those api  are sometimes showing wrong information so i thought why not directly scrap from website and cron job it and cache the data

**Comment by Codensity30** [comment]
Okay, we need to create a endpoint which fetch data from codechef and provide it in json form to frontend. 
Let me know if something is wrong.

**Comment by Ayushpanditmoto** [comment]
Current we only need endpoint only

**Comment by Ayushpanditmoto** [comment]
@Codensity30 can you do this in fastapi python you can make another folder name backend

**Comment by Codensity30** [comment]
nope, I'm familiar with Express.js and Axios I can go with that.

**Comment by Codensity30** [comment]
shall I create the endpoint using Express and Axios?

**Comment by Ayushpanditmoto** [comment]
@Codensity30 yep

**Comment by Codensity30** [comment]
I've figured that Codeforces uses [this](https://codeforces.com/data/contests) endpoint to get the contest data on their website, using POST method so that they can authenticate the request at the backend due to which when we try to fetch data we get "403 - Forbidden".
![image](https://github.com/Ayushpanditmoto/projectshub/assets/129579058/bb4aff80-99d9-49f9-b101-bdef3c1efa1b)

So I don't think we can get the data from the official endpoint, let me check for Codechef also.

**Comment by Codensity30** [comment]
I've checked for Codechef they provide an official endpoint that can be used to fetch data, so I'm working on it. By the way, do we only need future contests?

**Comment by Ayushpanditmoto** [comment]
@Codensity30  yes
