### ISSUE TITLE
No hyperlink is working in README.md

### ISSUE THREAD

**Issue by Rajeevjewar** [Ayushpanditmoto/projectshub#49]
There is no link working in the Readme file.
It shows error something like this below 👇
<img width="672" alt="Screenshot 2023-09-19 at 4 28 04 PM" src="https://github.com/Ayushpanditmoto/projectshub/assets/97542658/2b78755e-6413-4028-bcbc-13572f0896d1">

**Comment by Ayushpanditmoto** [comment]
@Rajeevjewar Remove All the links

**Comment by Rajeevjewar** [comment]
Ok..
