### ISSUE TITLE
Change the Website Title 

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/projectshub#5]

**Comment by Ayushpanditmoto** [comment]
Use NextSeo

**Comment by mathanraj0601** [comment]
@Ayushpanditmoto Can you describe the issue I'd like to work on?

**Comment by kiranrega** [comment]
are anyone working on this issue ?

**Comment by shivamsethi** [comment]
@Ayushpanditmoto  - I can work on this. Can you share the new title of the website and assign the issue to me?

**Comment by Sumitwarrior7** [comment]
i want to work on it. If you assigned me this task , i will tell you great titles for your website which upon your confirmation can be used as a title

**Comment by Ayushpanditmoto** [comment]
@shivamsethi use NextSeo You can youtube  New Title will be same make it reusable components

**Comment by shivamsethi** [comment]
@Ayushpanditmoto  - Just to understand clearly, a couple of questions below:

1. The current website title is **_ProjectsHub_**. The new title should be the same - Right?
2. You need a flexible reusable SEO component that can take the title, description, etc in props and can be used at any route or component in your nextjs app - Right? Something like [this](https://www.codeconcisely.com/posts/nextjs-seo-component/#creating-a-seo-component)

**Comment by Ayushpanditmoto** [comment]
Yes exactly

**Comment by shivamsethi** [comment]
@Ayushpanditmoto  - Can you assign it to me?

**Comment by shivamsethi** [comment]
@Ayushpanditmoto  - A couple of points here:

1. The **next-seo** package is only recommended for the **_pages_** directory and not for the **_app_** directory. We have **_app_** directory, so best to use the **_metadata_** and **_generateMetaData_** to generate metadata. Check [here](https://github.com/garmeeh/next-seo#readme:~:text=Note%20on%20app%20directory)
2. For app directory projects, Nextjs has the **_metadata_** and **_generateMetaData_** things to handle SEO directly. I doubt if we really need a reusable component. Even if we wish to, it's written in the docs that we can **_Export a static metadata object or a dynamic generateMetadata function in a layout.js or page.js file._**. Check [here](https://nextjs.org/docs/app/building-your-application/optimizing/metadata#usage). I mean, the most we could do is make a helper function that would export **_metadata_** object for us and we would have to export our helper function from our page.js or layout.js files.

**Comment by Ayushpanditmoto** [comment]
@shivamsethi great idea, implement which ever you thing helpful

**Comment by shivamsethi** [comment]
@Ayushpanditmoto  - Cool. So I will make a helper function that will help set static metadata for us. Will enable title and description for now but more meta can be enabled later when needed in the helper :)
