### ISSUE TITLE
Create a Dynamic routes

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/projectshub#56]
https://www.projectshub.org/flutter
https://www.projectshub.org/python
https://www.projectshub.org/backend
.. many more 

![Screenshot_4](https://github.com/Ayushpanditmoto/projectshub/assets/31253617/ef89e353-9081-4c73-baf7-549e845c839b)
![Screenshot_5](https://github.com/Ayushpanditmoto/projectshub/assets/31253617/245f30ed-1085-498e-91cd-db729897666e)

**Comment by ivanosquis10** [comment]
Would it be just to create the dynamic routes for each project? just like in the image above my friend?

**Comment by Ayushpanditmoto** [comment]
@ivanosquis10 yeah if that route not available redirect to not found page

**Comment by ivanosquis10** [comment]
Done friend! Thank u!
