### ISSUE TITLE
Need help in Creating blogs section

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/projectshub#7]

**Comment by imanirak** [comment]
What did you have in mind for the blogs? Did you want to integrate a CMS?

**Comment by Ayushpanditmoto** [comment]
@imanirak, my current plan is to utilize a local markdown file for faster loading, and I'm not inclined to employ a CMS at this time. However, we can always consider integrating one in the future as we progress through the website development journey.

**Comment by imanirak** [comment]
got it, I can try taking this on. If I come across anything too unfamiliar I'll ask for input @Ayushpanditmoto
