### ISSUE TITLE
UI / UX Need Figma Designer 

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Ayushpanditmoto/projectshub#8]
Redesign all the ideas

**Comment by imanirak** [comment]
Can you add more info, what do you mean all ideas? This might clear it up for a first timer looking to jump on this opportunity.

**Comment by sergomen** [comment]
I'm not a UX/UI designer, but I can work on it, cause I'm learning this interesting way to create apps. So, if you need some research or create CJM, feel free to ask.
In other hand, I need someone to help me too. I don't know English well (but I'm still learning). If you found some gramma mistakes or misuse of words, pls tell me about it. I will be very grateful.

**Comment by yogendra131994** [comment]
Hey @sergomen, I would love to work along with you for solving this issue.

**Comment by rizzabh** [comment]
Hey! how can i work on it with you guys? I have some experience in creating designs for opensource websites but still a rookie!

**Comment by vishesh-hue** [comment]
@Ayushpanditmoto  baap ke naukar h bsd?
